services:
  db_gym:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./modules/db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    networks:
      - default

  gym:
    build: ./
    ports:
      - 30004:30004
    depends_on:
      - db_gym
    networks:
      - skynet
      - default

networks:
  skynet:
    external: true
  default:
    external: false
